augment:
    mode:
    - time_shifting_batch
data:
    feature: data/dev/feature.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    stratified: True
dataloader_args:
    batch_size: 32
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.0008

epochs: 100
model:
    type: Crnn_res
    args: {
              dropout: 0.3,
              enlarge: 4
    }

outputpath: experiments/batch/
